services:
  app:
    image: ingenieriasoftwareaplicada
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ingenieriaSoftwareAplicada
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/ingenieriaSoftwareAplicada
      - SPRING_DOCKER_COMPOSE_ENABLED=false
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=ingenieriaSoftwareAplicada
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10
