services:
  postgresql:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=ingenieriaSoftwareAplicada
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10
